import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../../common/CommonWidgets.dart';
import '../../common/Constants.dart';
import '../../common/Extentions.dart';
import '../Controller/ApproveDiagnosisDetailsController.dart';
import '../Model/RequestDetails.dart';

class ApproveDiagnosisServiceWidget extends StatelessWidget {
  late RequestDetails details;

  ApproveDiagnosisServiceWidget(this.details);

  ApproveDiagnosisDetailsController controller =
      Get.put(ApproveDiagnosisDetailsController());

  @override
  Widget build(BuildContext context) {
    controller.details = details;
    return SafeArea(
      child: Scaffold(
        appBar: AppBar(title: Text('Approve Diagnose Details')),
        body: SingleChildScrollView(
          child: Container(
            child: Form(
              key: controller.requestFormKey,
              child: _getBody(),
            ),
          ),
        ),
      ),
    );
  }

  _getBody() {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        getCommonSectionHeaderWidget(details.title, Alignment.center),
        getCommonLabelWidget(details.getReferenceNumberText(), 'Ref.No'),
        getCommonLabelWidget(
            getStringFromTimestamp(details.createdDate), CCreatedDate),
        getCommonLabelWidget(details.equipment?.name, CEquipmentName),
        if (details.isAutoGenerated)
          getCommonLabelWidget(
              details.equipment?.scheduleMaintenancePeriodInDays,
              CScheduledMaintenancePeriodDays),
        getCommonLabelWidget(details.getAutogeneratedText(), CAutoGenerated),
        if (details.requestPhotoUrls.isNotEmpty == true)
          getCommonRemoteImageWidget(
              details.requestPhotoUrls[0], "Issue image"),
        if (details.requestVideoUrls.isNotEmpty == true)
          getCommonRemoteVideoWidget(
              details.requestVideoUrls.first, "Issue Video"),
        if (details.description.isNotEmpty == true)
          getCommonSectionWidget('Issue Details', details.description),
        getCommonLabelWidget(
            getStringFromTimestamp(details.scheduledDateTime), CScheduledDate),
        getCommonLabelWidget(
            getStringFromTimestamp(details.servicedDateTime), CServicedDate),
        getCommonLabelWidget(details.serviceEngineerName, 'Service Done By'),
        getCommonLabelWidget(details.getShortStatusText(), 'Status'),
        if (details.servicePhotoUrls.isNotEmpty == true)
          getCommonRemoteImageWidget(
              details.servicePhotoUrls[0], "Diagnosis image"),
        if (details.serviceEngineerComment.isNotEmpty == true)
          getCommonSectionWidget('Comment', details.serviceEngineerComment),
        _getAddAndPreviewPdfReportWidget(),
        getCommonBackgroundWidget(18.0),
        getCommonExpandedButton("Approve Diagnosis", controller.approveAction),
        getCommonBackgroundWidget(24.0),
      ],
    );
  }

  _getAddAndPreviewPdfReportWidget() {
    return Obx(() {
      return getCommonAddAndPreviewPdfWidget(controller.pdfServiceReport);
    });
  }
}
